# Generated by Django 5.2 on 2025-04-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dublicate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(unique=True)),
                ('text', models.CharField(max_length=254)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
