# Generated by Django 5.2 on 2025-04-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedublicate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dublicate',
            name='text',
            field=models.TextField(),
        ),
    ]
